export enum HTTP_RC {
  SUCCESS = 200,
  CREATED = 201,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  TOO_MANY_REQUESTS = 429,
  SERVER_ERROR = 500,
}

export enum REQUEST_TYPE {
  GET = "GET",
  POST = "POST",
}
