export enum ERRORS {
  GENERIC = "GENERIC_ERROR",
  NETWORK = "NETWORK_ERROR",
  INCORRECT_REQUEST_DATA = "INCORRECT_REQUEST_DATA",
  INCORRECT_ARGUMENT_RECIEVED = "INCORRECT_ARGUMENT_RECIEVED",
  REMOTE_DATA_NOT_FOUND = "REMOTE_DATA_NOT_FOUND",
  SERVER = "SERVER_ERROR",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
}
