import {ERRORS} from "../constants/errors";

export type Error_T = ERRORS.GENERIC & ERRORS.INCORRECT_ARGUMENT_RECIEVED & HTTPError;

export type HTTPError =
  | ERRORS.INCORRECT_REQUEST_DATA
  | ERRORS.NETWORK
  | ERRORS.REMOTE_DATA_NOT_FOUND
  | ERRORS.SERVER
  | ERRORS.TOO_MANY_REQUESTS;
